module Redis::Keys
  USER_VOTE_HSET         = "USER_VOTE_HSET:%{user_id}"
  DISCUSSION_VIEW_COUNT  = "DISCUSSION_VIEW_COUNT:%{discussion_id}"
  ANSWER_VIEW_COUNT      = "ANSWER_VIEW_COUNT:%{answer_id}"
  UNANSWERED_COUNT       = "UNANSWERED_COUNT"
  SPAMMED_COUNT          = "SPAMMED_COUNT"
  UNPUBLISHED_COUNT      = "UNPUBLISHED_COUNT"
  AVG_SENTIMENT_SCORE    = "AVG_SENTIMENT_SCORE"
end